Fix: internet check + correct perms + tty + custom sddm

diff --git a/setup-hypr/install b/setup-hypr/install
--- a/setup-hypr/install
+++ b/setup-hypr/install
@@ -68,7 +68,7 @@ MINIMAL_PACKAGES=(
 )
 
 EXTENDED_PACKAGES=(
-"brave-bin"
+"firefox"
 "emacs"
 "vencord-desktop-bin"
 "thunar"
@@ -194,7 +194,7 @@ copy_config() {
     rm -rf ~/.bin;              cp -r    ../configs/.bin ~ &&         echo -e "[${BLUE}ok${RESET}] Copied .icons to ~/.icons"
 
     # Set some files as exacutable 
-    chmod +x ~/.config/hypr/xdg-portal-hyprland && echo -e "[${BLUE}ok${RESET}] '~/.config/hypr/xdg-portal-hyprland' is executable: .wxr-xr-x "
+    chmod +x ~/.config/hypr/scripts/xdg-portal-hyprland && echo -e "[${BLUE}ok${RESET}] '~/.config/hypr/xdg-portal-hyprland' is executable: .wxr-xr-x "
     chmod +x ~/.config/swww/scripts/init_wallpaper && echo -e "[${BLUE}ok${RESET}] '~/config/swww/scripts/init_wallpaper' is executable: .wxr-xr-x "
     chmod +x ~/.config/swww/scripts/change_wallpaper && echo -e "[${BLUE}ok${RESET}] '~/.config/swww/scripts/change_wallpaper' is executable: .wxr-xr-x "
     chmod +x ~/.config/waybar/scripts/waybar-wttr.py && echo -e "[${BLUE}ok${RESET}] '~/.config/waybar/scripts/waybar-wttr.py' is executable: .wxr-xr-x "
@@ -248,16 +248,24 @@ install_sddm() {
         done
 
         if [[ $SDDM_CUSTOM_INSTALL == "y" || $SDDM_CUSTOM_INSTALL == "Y" || $SDDM_CUSTOM_INSTALL == "" ]]; then
-            git clone https://github.com/POP303U/rose-pine-sddm.git ~/rose-pine-sddm >/dev/null 2>&1
+            sudo rm -rf /usr/share/sddm/themes/rose-pine-sddm
+            git clone https://github.com/POP303U/rose-pine-sddm ~/rose-pine-sddm >/dev/null 2>&1
             sudo mv ~/rose-pine-sddm /usr/share/sddm/themes/
             sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /etc/sddm.conf
-            sudo sed -i 's/\(Current=\).*/\1rose-pine-sddm/' /etc/sddm.conf
+            # use sed for modifying the theme
+            sudo sed -i 's|Current=.*|Current=rose-pine-sddm|' /etc/sddm.conf
+            sudo sed -i 's|CursorSize=.*|CursorSize=24|' /etc/sddm.conf
+            sudo sed -i 's|CursorTheme=.*|CursorTheme=Bibata-Modern-Classic|' /etc/sddm.conf
             echo -e "[${BLUE}ok${RESET}] Installed custom adaptive sddm theme"
 
             # time to get hacky, dont want to create extra repo so here we areee
             sed -i 's|Background="Backgrounds/cat_leaves.png"|Background="Backgrounds/current"|' /usr/share/sddm/themes/rose-pine-sddm/theme.conf
             sed -i 's|PartialBlur="false"|PartialBlur="true"|' /usr/share/sddm/themes/rose-pine-sddm/theme.conf
             sed -i 's|BlueRadius="0"|BlurRadius="15"|' /usr/share/sddm/themes/rose-pine-sddm/theme.conf
+
+            # why
+            CURRENT_BG="$(cat ../configs/.config/swww/current/name)"
+            sudo cp ../configs/.config/swww/walls/Rose-Pine/$CURRENT_BG /usr/share/sddm/themes/rose-pine-sddm/Backgrounds 
         else 
             echo -e "[${PURPLE}info${RESET}] Skipping custom sddm theme"
         fi
@@ -277,7 +285,11 @@ install_and_apply_tty() {
             fi
         done
 
-        echo 'FONT=ter-v28b' | sudo tee -a /etc/vconsole.conf
+        
+        echo -e "[${PURPLE}info${RESET}] The following has been added to /etc/vconsole.conf"
+        echo -e '\nFONT=ter-v28b\n' | sudo tee -a /etc/vconsole.conf
+        sudo rm -f /etc/issue ; sudo cp -r ../configs/etc/issue /etc && echo -e "[${BLUE}ok${RESET}] Copied issue to /etc/issue"
+        sudo rm -f /etc/motd ; sudo cp -r ../configs/etc/motd /etc && echo -e "[${BLUE}ok${RESET}] Copied motd to /etc/motd"
     fi
 }
 
@@ -378,70 +390,82 @@ stage_4() {
     enable_sddm_quest
 }
 
-# https://patorjk.com/software/taag/#p=display&f=Slant&t=Hyprland
-echo -e "
-${GREEN}    __  __                 __                __
-${GREEN}   / / / /_  ______  _____/ /___ _____  ____/ /
-${GREEN}  / /_/ / / / / __ \/ ___/ / __ '/ __ \/ __  / 
-${GREEN} / __  / /_/ / /_/ / /  / / /_/ / / / / /_/ /  
-${GREEN}/_/ /_/\__, / .___/_/  /_/\__,_/_/ /_/\__,_/   
-${GREEN}      /____/_/                                 ${RESET}
+get_options() {
+    # https://patorjk.com/software/taag/#p=display&f=Slant&t=Hyprland
+    echo -e "
+    ${GREEN}    __  __                 __                __
+    ${GREEN}   / / / /_  ______  _____/ /___ _____  ____/ /
+    ${GREEN}  / /_/ / / / / __ \/ ___/ / __ '/ __ \/ __  / 
+    ${GREEN} / __  / /_/ / /_/ / /  / / /_/ / / / / /_/ /  
+    ${GREEN}/_/ /_/\__, / .___/_/  /_/\__,_/_/ /_/\__,_/   
+    ${GREEN}      /____/_/                                 ${RESET}
 
-# ${YELLOW}Easy Hyprland installer${RESET} #
+    # ${YELLOW}Easy Hyprland installer${RESET} #
 
-${WHITE_BOLD}Tip: See installed packages at the top of the script${RESET}
-${CYAN}1${RESET}. Base 
-${CYAN}2${RESET}. Minimal
-${CYAN}3${RESET}. Extended
-${CYAN}4${RESET}. Gaming
-"
-read -n1 -rep "(1/2/3/4) $: " STAGE
+    ${WHITE_BOLD}Tip: See installed packages at the top of the script${RESET}
+    ${CYAN}1${RESET}. Base 
+    ${CYAN}2${RESET}. Minimal
+    ${CYAN}3${RESET}. Extended
+    ${CYAN}4${RESET}. Gaming
+    "
+    read -n1 -rep "(1/2/3/4) $: " STAGE
 
-echo -e "
-${GREEN}   _____     __    __         
-${GREEN}  / ___/____/ /___/ /___ ___  
-${GREEN}  \__ \/ __  / __  / __ '__ \ 
-${GREEN} ___/ / /_/ / /_/ / / / / / / 
-${GREEN}/____/\__,_/\__,_/_/ /_/ /_/  ${RESET}
-"
-echo -e "\n${WHITE_BOLD}Install sddm? ${RESET}"
-read -n1 -rep "(y/n) $: " SDDM_INSTALL
+    echo -e "
+    ${GREEN}   _____     __    __         
+    ${GREEN}  / ___/____/ /___/ /___ ___  
+    ${GREEN}  \__ \/ __  / __  / __ '__ \ 
+    ${GREEN} ___/ / /_/ / /_/ / / / / / / 
+    ${GREEN}/____/\__,_/\__,_/_/ /_/ /_/  ${RESET}
+    "
+    echo -e "\n${WHITE_BOLD}Install sddm? ${RESET}"
+    read -n1 -rep "(y/n) $: " SDDM_INSTALL
 
-if [[ $SDDM_INSTALL == "y" || $SDDM_INSTALL == "Y" || $SDDM_INSTALL == "" ]]; then
-    echo -e "${WHITE_BOLD}\nInstall custom adaptive sddm? [https://github.com/POP303U/rose-pine-sddm]${RESET}"
-    read -n1 -rep "(y/n) $: " SDDM_CUSTOM_INSTALL
+    if [[ $SDDM_INSTALL == "y" || $SDDM_INSTALL == "Y" || $SDDM_INSTALL == "" ]]; then
+        echo -e "${WHITE_BOLD}\nInstall custom adaptive sddm? [https://github.com/POP303U/rose-pine-sddm]${RESET}"
+        read -n1 -rep "(y/n) $: " SDDM_CUSTOM_INSTALL
+    fi
+
+    echo -e "
+    ${GREEN}    ____             __ 
+    ${GREEN}   / __ \__  _______/ /_
+    ${GREEN}  / /_/ / / / / ___/ __/
+    ${GREEN} / _, _/ /_/ (__  ) /_  
+    ${GREEN}/_/ |_|\__,_/____/\__/  ${RESET}
+    "
+    echo -e "${WHITE_BOLD}Install beautiful ls/cat/find -> eza/bat/fd? ${RESET}"
+    echo -e "${WHITE_BOLD}Preview: ${RESET}"
+    echo -e "---------------------------------------------------
+    [4mPermissions[0m  [4mSize[0m [4mUser[0m [4mDate Modified[0m [4mName[0m
+    [1;34md[33mr[31mw[32mx[0m[33mr[1;90m-[0m[32mx[33mr[1;90m-[0m[32mx[0m      [1;90m-[0m [1;33mpops[0m [34m 3 Feb 15:02[0m  [1;34mconfigs[0m
+    [1;34md[33mr[31mw[32mx[0m[33mr[1;90m-[0m[32mx[33mr[1;90m-[0m[32mx[0m      [1;90m-[0m [1;33mpops[0m [34m 3 Feb 13:40[0m  [1;34mconfigs_backup[0m
+    [1;34md[33mr[31mw[32mx[0m[33mr[1;90m-[0m[32mx[33mr[1;90m-[0m[32mx[0m      [1;90m-[0m [1;33mpops[0m [34m25 Jan 16:20[0m  [1;34mdebug[0m
+    .[1;33mr[31mw[90m-[0m[33mr[1;90m--[0m[33mr[1;90m--[0m  [1;32m1.0Ki[0m [1;33mpops[0m [34m30 Dec  2023[0m  LICENSE
+    .[1;33mr[31mw[90m-[0m[33mr[1;90m--[0m[33mr[1;90m--[0m  [1;32m2.2Ki[0m [1;33mpops[0m [34m20 Jan 15:56[0m  [1;4;33mREADME.md[0m
+    [1;34md[33mr[31mw[32mx[0m[33mr[1;90m-[0m[32mx[33mr[1;90m-[0m[32mx[0m      [1;90m-[0m [1;33mpops[0m [34m 3 Feb 15:16[0m  [1;34msetup-hypr[0m
+    ---------------------------------------------------"
+    read -n1 -rep "(y/n) $: " OPTIONAL_DEPS_RUST
+
+    echo -e "
+    ${GREEN}   __  __       
+    ${GREEN}  / /_/ /___  __
+    ${GREEN} / __/ __/ / / /
+    ${GREEN}/ /_/ /_/ /_/ / 
+    ${GREEN}\__/\__/\__, /  
+    ${GREEN}       /____/    ${RESET}
+    "
+    echo -e "\n${WHITE_BOLD}Install tty login? ${RESET}"
+    read -n1 -rep "(y/n) $: " TTY_INSTALL
+}
+
+# check for internet
+if ping -w 1 x.org >/dev/null 2>&1; then
+    echo -e "[${BLUE}ok${RESET}] Found internet connection" 
+else 
+    echo -e "[${RED}fail${RESET}] Internet connection required, please connect to a network!"
+    exit 1
 fi
 
-echo -e "
-${GREEN}    ____             __ 
-${GREEN}   / __ \__  _______/ /_
-${GREEN}  / /_/ / / / / ___/ __/
-${GREEN} / _, _/ /_/ (__  ) /_  
-${GREEN}/_/ |_|\__,_/____/\__/  ${RESET}
-"
-echo -e "${WHITE_BOLD}Install beautiful ls/cat/find -> eza/bat/fd? ${RESET}"
-echo -e "${WHITE_BOLD}Preview: ${RESET}"
-echo -e "---------------------------------------------------
-[4mPermissions[0m  [4mSize[0m [4mUser[0m [4mDate Modified[0m [4mName[0m
-[1;34md[33mr[31mw[32mx[0m[33mr[1;90m-[0m[32mx[33mr[1;90m-[0m[32mx[0m      [1;90m-[0m [1;33mpops[0m [34m 3 Feb 15:02[0m  [1;34mconfigs[0m
-[1;34md[33mr[31mw[32mx[0m[33mr[1;90m-[0m[32mx[33mr[1;90m-[0m[32mx[0m      [1;90m-[0m [1;33mpops[0m [34m 3 Feb 13:40[0m  [1;34mconfigs_backup[0m
-[1;34md[33mr[31mw[32mx[0m[33mr[1;90m-[0m[32mx[33mr[1;90m-[0m[32mx[0m      [1;90m-[0m [1;33mpops[0m [34m25 Jan 16:20[0m  [1;34mdebug[0m
-.[1;33mr[31mw[90m-[0m[33mr[1;90m--[0m[33mr[1;90m--[0m  [1;32m1.0Ki[0m [1;33mpops[0m [34m30 Dec  2023[0m  LICENSE
-.[1;33mr[31mw[90m-[0m[33mr[1;90m--[0m[33mr[1;90m--[0m  [1;32m2.2Ki[0m [1;33mpops[0m [34m20 Jan 15:56[0m  [1;4;33mREADME.md[0m
-[1;34md[33mr[31mw[32mx[0m[33mr[1;90m-[0m[32mx[33mr[1;90m-[0m[32mx[0m      [1;90m-[0m [1;33mpops[0m [34m 3 Feb 15:16[0m  [1;34msetup-hypr[0m
----------------------------------------------------"
-read -n1 -rep "(y/n) $: " OPTIONAL_DEPS_RUST
-
-echo -e "
-${GREEN}   __  __       
-${GREEN}  / /_/ /___  __
-${GREEN} / __/ __/ / / /
-${GREEN}/ /_/ /_/ /_/ / 
-${GREEN}\__/\__/\__, /  
-${GREEN}       /____/    ${RESET}
-"
-echo -e "\n${WHITE_BOLD}Install tty fonts? ${RESET}"
-read -n1 -rep "(y/n) $: " TTY_INSTALL
+get_options
 
 if [[ $STAGE -lt 1 || $STAGE -gt 4 ]]; then 
     echo -e "${RED}Choose a valid option${RESET}"
